// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace $safeprojectname$
{
    using Microsoft.AspNet.Identity.EntityFramework;
    using System;

    // Devices
    public class DeviceConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Device>
    {
        public DeviceConfiguration()
            : this("dbo")
        {
        }
 
        public DeviceConfiguration(string schema)
        {
            ToTable(schema + ".Devices");
            HasKey(x => x.DeviceId);

            Property(x => x.DeviceId).HasColumnName("DeviceID").IsRequired().HasColumnType("bigint").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Type).HasColumnName("Type").IsRequired().HasColumnType("smallint");
            Property(x => x.Name).HasColumnName("Name").IsRequired().HasColumnType("nvarchar").HasMaxLength(500);
            Property(x => x.Status).HasColumnName("Status").IsRequired().HasColumnType("bit");
            Property(x => x.CreatedOnDate).HasColumnName("CreatedOnDate").IsRequired().HasColumnType("datetime");
            Property(x => x.CreatedByUserId).HasColumnName("CreatedByUserID").IsOptional().HasColumnType("int");
            Property(x => x.LastModifiedOnDate).HasColumnName("LastModifiedOnDate").IsRequired().HasColumnType("datetime");
            Property(x => x.LastModifiedByUserId).HasColumnName("LastModifiedByUserID").IsOptional().HasColumnType("int");
        }
    }

}
// </auto-generated>
