// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace $safeprojectname$
{
    using Microsoft.AspNet.Identity.EntityFramework;
    using System;

    // Devices
    public class Device
    {
        public long DeviceId { get; set; } // DeviceID (Primary key)
        public short Type { get; set; } // Type
        public string Name { get; set; } // Name
        public bool Status { get; set; } // Status
        public System.DateTime CreatedOnDate { get; set; } // CreatedOnDate
        public int? CreatedByUserId { get; set; } // CreatedByUserID
        public System.DateTime LastModifiedOnDate { get; set; } // LastModifiedOnDate
        public int? LastModifiedByUserId { get; set; } // LastModifiedByUserID
    }

}
// </auto-generated>
